# Generated by Django 5.2.1 on 2025-07-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_admin', '0011_rename_user_bibliotecario_perfilbibliotecario'),
        ('user_bibliotecario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_conteudo', models.TextField()),
                ('texto_conteudo', models.TextField()),
                ('img_capa_conteudo', models.ImageField(null=True, upload_to='img_lib/%Y/%m/%d/')),
                ('validado', models.BooleanField(default=False)),
                ('campus_conteudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudo_campus', to='user_admin.campus')),
                ('categoria_conteudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudo_categoria', to='user_admin.categoria')),
                ('curso_conteudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudo_curso', to='user_admin.curso')),
                ('instituicao_conteudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudo_instituicao', to='user_admin.instituicao')),
                ('tipos_conteudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudo_tipos', to='user_admin.tipos')),
                ('tutor_conteudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudo_tutor', to='user_bibliotecario.perfilprofessor')),
            ],
        ),
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudo_autor', to=settings.AUTH_USER_MODEL)),
                ('conteudo_cai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudo_autores', to='conteudos.conteudoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoAdicionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pdfs/%Y/%m/%d/')),
                ('conteudo_cai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudo_adicional', to='conteudos.conteudoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Midias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_conteudo', models.ImageField(blank=True, null=True, upload_to='img_lib/%Y/%m/%d/')),
                ('conteudo_cai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudo_midia', to='conteudos.conteudoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_conteudo', models.URLField()),
                ('conteudo_cai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudo_referencia', to='conteudos.conteudoacademico')),
            ],
        ),
    ]
