# Generated by Django 5.2.1 on 2025-07-25 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0002_alter_autores_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoadicionais',
            name='arquivo',
            field=models.FileField(upload_to='pdfs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'txt'])]),
        ),
    ]
