# Generated by Django 5.2.1 on 2025-07-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0003_alter_conteudoadicionais_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencias',
            name='referencia_conteudo',
            field=models.URLField(max_length=2000),
        ),
    ]
