# Generated by Django 5.2.1 on 2025-07-29 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0004_alter_referencias_referencia_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoacademico',
            name='data_envio',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
