# Generated by Django 5.2.1 on 2025-08-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0006_alter_autores_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoacademico',
            name='descricao_conteudo',
            field=models.CharField(max_length=1500),
        ),
    ]
