# Generated by Django 5.2.1 on 2025-08-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0007_alter_conteudoacademico_descricao_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoacademico',
            name='qtd_favoritos',
            field=models.IntegerField(default=0),
        ),
    ]
