# Generated by Django 5.2.1 on 2025-08-08 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0008_conteudoacademico_qtd_favoritos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaFavoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_cai', models.ManyToManyField(related_name='conteudo_favorito', to='conteudos.conteudoacademico')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
