# Generated by Django 5.2.1 on 2025-08-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0009_caixafavoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoacademico',
            name='qtd_favoritos',
            field=models.IntegerField(),
        ),
    ]
