# Generated by Django 5.2.1 on 2025-08-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0010_alter_conteudoacademico_qtd_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoacademico',
            name='qtd_favoritos',
            field=models.IntegerField(default=0),
        ),
    ]
