# Generated by Django 5.2.1 on 2025-08-10 01:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0011_alter_conteudoacademico_qtd_favoritos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_capa', models.ImageField(blank=True, null=True, upload_to='img_lib/%Y/%m/%d/')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_conteudo', models.TextField()),
                ('tipo_conteudo', models.CharField(default='Conteúdo Externo', max_length=50)),
                ('link_conteudo', models.URLField(max_length=2000)),
                ('data_envio', models.DateField(default=datetime.datetime.now)),
                ('criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
