# Generated by Django 5.2.1 on 2025-08-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0012_conteudoexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoexterno',
            name='qtd_favorito_ex',
            field=models.IntegerField(default=0),
        ),
    ]
