# Generated by Django 5.2.1 on 2025-08-10 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0013_conteudoexterno_qtd_favorito_ex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaFavoritosExternos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_ce', models.ManyToManyField(related_name='conteudo_favorito_ex', to='conteudos.conteudoexterno')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_favoritos_ex', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
