# Generated by Django 5.2.1 on 2025-08-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0014_caixafavoritosexternos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conteudoexterno',
            old_name='qtd_favorito_ex',
            new_name='qtd_favoritos',
        ),
    ]
