# Generated by Django 5.2.1 on 2025-08-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0015_rename_qtd_favorito_ex_conteudoexterno_qtd_favoritos'),
        ('user_admin', '0013_alter_campus_nome_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoexterno',
            name='Campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='externo_campus', to='user_admin.campus'),
        ),
    ]
