# Generated by Django 5.2.1 on 2025-08-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0016_conteudoexterno_campus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conteudoexterno',
            old_name='Campus',
            new_name='campus_conteudo',
        ),
    ]
