# Generated by Django 5.2.1 on 2025-06-19 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_admin', '0011_rename_user_bibliotecario_perfilbibliotecario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_user', models.CharField(default='aluno', max_length=50)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='img_lib/%Y/%m/%d/')),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_campus', to='user_admin.campus')),
                ('criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_criador', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_curso', to='user_admin.curso')),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_instituicao', to='user_admin.instituicao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_user', models.CharField(default='professor', max_length=50)),
                ('formacao', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='img_lib/%Y/%m/%d/')),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor_campus', to='user_admin.campus')),
                ('criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor_criador', to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor_instituicao', to='user_admin.instituicao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
