# Generated by Django 5.2.1 on 2025-08-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0006_alter_autores_autor'),
        ('notificacao', '0003_alter_notificacao_remetente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='conteudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conteudos.conteudoacademico'),
        ),
    ]
