# Generated by Django 5.2.1 on 2025-08-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0004_alter_notificacao_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='titulo_notificacao',
            field=models.CharField(max_length=300),
        ),
    ]
