# Generated by Django 5.2.1 on 2025-05-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiladmin',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='img_lib/%Y/%m/%d/'),
        ),
    ]
