# Generated by Django 5.2.1 on 2025-05-30 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_alter_perfiladmin_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=50)),
                ('administradores', models.ManyToManyField(related_name='instituicao_admin', to=settings.AUTH_USER_MODEL)),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituicao_criada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
