# Generated by Django 5.2.1 on 2025-05-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0003_instituicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='administradores',
        ),
    ]
