# Generated by Django 5.2.1 on 2025-06-04 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_curso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campus', models.CharField(max_length=100)),
                ('email_campus', models.EmailField(max_length=100)),
                ('endereco_campus', models.CharField(max_length=200)),
                ('cidade_campus', models.CharField(max_length=100)),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_criado', to=settings.AUTH_USER_MODEL)),
                ('cursos_campus', models.ManyToManyField(blank=True, related_name='campus_curso', to='user_admin.curso')),
            ],
        ),
    ]
