# Generated by Django 5.2.1 on 2025-06-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0007_categoria_tipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='instituicao_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_instituicao', to='user_admin.instituicao'),
        ),
    ]
