# Generated by Django 5.2.1 on 2025-06-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0008_campus_instituicao_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='instituicao_campus',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, related_name='campus_instituicao', to='user_admin.instituicao'),
            preserve_default=False,
        ),
    ]
