# Generated by Django 5.2.1 on 2025-06-10 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0009_alter_campus_instituicao_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Bibliotecario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_user', models.CharField(default='bibliotecario', max_length=50)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='img_lib/%Y/%m/%d/')),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliotecario_campus', to='user_admin.campus')),
                ('criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliotecario_criador', to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliotecario_instituicao', to='user_admin.instituicao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_bibliotecario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
