# Generated by Django 5.2.1 on 2025-06-10 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0010_user_bibliotecario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Bibliotecario',
            new_name='PerfilBibliotecario',
        ),
    ]
