# Generated by Django 5.2.1 on 2025-07-28 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0011_rename_user_bibliotecario_perfilbibliotecario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiladmin',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
