# Generated by Django 5.2.1 on 2025-07-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0012_alter_perfiladmin_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='nome_campus',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome_instituicao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tipos',
            name='nome_tipo',
            field=models.CharField(max_length=200),
        ),
    ]
